# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_poc/resources/*
# and mlops_poc/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for mlops_poc Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_poc

env:
  ## Microsoft Entra ID SP authentication
  # ARM_TENANT_ID: ${{ env.STAGING_ARM_TENANT_ID }}
  # ARM_CLIENT_ID: ${{ env.STAGING_ARM_CLIENT_ID }}
  # ARM_CLIENT_SECRET: ${{ env.STAGING_ARM_CLIENT_SECRET }}
  ## OAuth machine-to-machine (M2M) authentication
  DATABRICKS_CLIENT_ID: ${{ secrets.DB_SP_CLIENT_ID}}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DB_SP_CLIENT_SECRET}}
  

jobs:
  prod:
    environment: production
    concurrency: mlops_poc-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.225.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t aimlops_prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t aimlops_prod
