name: Feature and Training Unit and Integration Tests for mlops_poc
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'mlops_poc/**'
      - '.github/workflows/mlops_poc-run-tests.yml'

defaults:
  run:
    working-directory: ./mlops_poc/

env:
  ## Microsoft Entra ID SP authentication
  # ARM_TENANT_ID: ${{ env.STAGING_ARM_TENANT_ID }}
  # ARM_CLIENT_ID: ${{ env.STAGING_ARM_CLIENT_ID }}
  # ARM_CLIENT_SECRET: ${{ env.STAGING_ARM_CLIENT_SECRET }}
  ## OAuth machine-to-machine (M2M) authentication
  DATABRICKS_CLIENT_ID: ${{ secrets.DB_SP_CLIENT_ID}}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DB_SP_CLIENT_SECRET}}
  

concurrency: mlops_poc-feature-training-integration-test-staging

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      # Feature store tests bring up a local Spark session, so Java is required.
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      - name: Run tests with pytest
        run: |
            pytest

  integration_test:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.225.0
      - name: Validate Bundle For Test Deployment Target in Staging Workspace
        id: validate
        run: |
          databricks bundle validate -t aimlops_staging
      - name: Deploy Bundle to Test Deployment Target in Staging Workspace
        id: deploy
        run: |
          databricks bundle deploy -t aimlops_staging
      - name: Run Feature Engineering Workflow for Test Deployment Target in Staging Workspace
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t aimlops_staging
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        run: |
          databricks bundle run model_training_job -t aimlops_staging
